version: 2

models:
  - name: meey_id_transformation_user_count_by_status
    columns:
      - name: status
        description: '{{ doc("orders_status") }}'

      - name: count
        description: Amount of the order (AUD) paid for by gift card
